### ISSUE TITLE
Can't use requests.get after doing a hook?

### ISSUE THREAD

**Issue by GuiSaiUwU** [chilaxan/fishhook#6]
Python 3.11.7
Requests module and fishhook probably the latest :3
if I use the get before using the hook(list) its print success
```python
from fishhook import hook
import requests
requests.get("https://google.com")
@hook(list)
def __add__(self, other):
    self.append(other)
    return self
print("success")
```
while the opposite gives a really big error
``` python
from fishhook import hook
import requests
@hook(list)
def __add__(self, other):
    self.append(other)
    return self
requests.get("https://google.com")
print("success")
```

the error:
```
Traceback (most recent call last):
  File "c:\Users\GuiSai\Desktop\nogetfishhook.py", line 10, in <module>
    requests.get("https://google.com")
  File "C:\Users\GuiSai\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GuiSai\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GuiSai\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 575, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GuiSai\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 483, in prepare_request
    auth = get_netrc_auth(request.url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GuiSai\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\utils.py", line 209, in get_netrc_auth
    from netrc import NetrcParseError, netrc
  File "C:\Users\GuiSai\AppData\Local\Programs\Python\Python311\Lib\netrc.py", line 5, in <module>
    import os, shlex, stat
  File "C:\Users\GuiSai\AppData\Local\Programs\Python\Python311\Lib\shlex.py", line 323, in <module>
    _find_unsafe = re.compile(r'[^\w@%+=:,./-]', re.ASCII).search
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GuiSai\AppData\Local\Programs\Python\Python311\Lib\re\__init__.py", line 227, in compile
    return _compile(pattern, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GuiSai\AppData\Local\Programs\Python\Python311\Lib\re\__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GuiSai\AppData\Local\Programs\Python\Python311\Lib\re\_compiler.py", line 749, in compile
    code = _code(p, flags)
           ^^^^^^^^^^^^^^^
  File "C:\Users\GuiSai\AppData\Local\Programs\Python\Python311\Lib\re\_compiler.py", line 579, in _code
    _compile_info(code, p, flags)
  File "C:\Users\GuiSai\AppData\Local\Programs\Python\Python311\Lib\re\_compiler.py", line 567, in _compile_info
    _compile_charset(charset, flags, code)
  File "C:\Users\GuiSai\AppData\Local\Programs\Python\Python311\Lib\re\_compiler.py", line 219, in _compile_charset
    for op, av in charset:
        ^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by chilaxan** [comment]
That hook modifies how lists behave, and requests.get likely depends on the normal behavior of lists. Since fishhook hooks are global, it breaks internally. This is probably expected. Does the same issue happen with a hook that does not modify the behavior like: ```py
from fishhook import hook, orig
@hook(list)
def __add__(self, other):
    print(self, other)
    return orig(self, other)
```

**Comment by GuiSaiUwU** [comment]
Thank you, adapted to work as how I was wanting to work with using isistance 👯 
```python
from fishhook import hook, orig
@hook(list)
def __add__(self, other):
    if isinstance(other, str):
        self.append(other)
        return self
    return orig(self, other)
```
